### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by xstortionist** [balupton/jquery-scrollto#36]
Can someone explain how you use this exactly?

This is what I'm doing currently:

`$('#whoweare').ScrollTo();`

`li #[a(href="#whoweare") Who We Are]`

There is no transition effect at all :/

**Comment by Inumedia** [comment]
Hi xstortionist,

I haven't had much trouble getting this to work, do you have an example site so I can dig into what's going on?

**Comment by xstortionist** [comment]
Sorry, I ended up building my own :/

**Comment by Inumedia** [comment]
No worries
